### ISSUE TITLE
Cants start .11

### ISSUE THREAD

**Issue by neopaf** [seene-club/Open-Seene#5]
Keeps crashing at start. Will attach crash logs a bit later

**Comment by neopaf** [comment]
now can. strange. trying to extract crash files...

**Comment by neopaf** [comment]
[Open Seene-2016-11-25-1.ips.txt](https://github.com/seene-club/Open-Seene/files/612926/Open.Seene-2016-11-25-1.ips.txt)

**Comment by seene-club** [comment]
Hi @neopaf this crash report is unsymbolicated (I can't read it).

Symbolicating Crash Reports With Xcode

Xcode will automatically attempt to symbolicate all crash reports that it encounters. All you need to do for symbolication is to add the crash report to the Xcode Organizer.

    Connect an iOS device to your Mac

    Choose "Devices" from the "Window" menu

    Under the "DEVICES" section in the left column, choose a device

    Click the "View Device Logs" button under the "Device Information" section on the right hand panel

    Drag your crash report onto the left column of the presented panel

    Xcode will automatically symbolicate the crash report and display the results

To symbolicate a crash report, Xcode needs to be able to locate the following:

    The crashing application's binary and dSYM file.

    The binaries and dSYM files for all custom frameworks that the application links against. For frameworks that were built from source with the application, their dSYM files are copied into the archive alongside the application's dSYM file. For frameworks that were built by a third-party, you will need to ask the author for the dSYM file.

    Symbols for the OS that the that application was running on when it crashed. These symbols contain debug information for the frameworks included in a specific OS release (e.g, iOS 9.3.3). OS symbols are architecture specific - a release of iOS for 64-bit devices won't include armv7 symbols. Xcode will automatically copy OS symbols from each device that you connect to your Mac.

If any of these are missing Xcode may not be able to symbolicate the crash report, or may only partially symbolicate the crash report.

**Comment by seene-club** [comment]
Does it start now? 
If not: try to delete and reinstall.

**Comment by neopaf** [comment]
It does now.

**Comment by seene-club** [comment]
Ok, we can reopen if you have problems again. closed for now.
