### ISSUE TITLE
I see no publisher name under a viewer

### ISSUE THREAD

**Issue by neopaf** [seene-club/Open-Seene#6]
only title (description?) now.
![img_4968](https://cloud.githubusercontent.com/assets/4362564/20620208/998b144a-b309-11e6-9f77-507fe668deb7.PNG)

**Comment by seene-club** [comment]
I will check this in Simulator...

**Comment by seene-club** [comment]
Now this should only happen in "zoomed" mode ... will fix soon!

**Comment by seene-club** [comment]
fixed for "zoom" mode as well!
