### ISSUE TITLE
iPad Icons

### ISSUE THREAD

**Issue by seene-club** [seene-club/Open-Seene#7]
@chiaroscurosity I have a compiler warning in XCode (see image)

![main icon assets warning](https://cloud.githubusercontent.com/assets/11654139/20623131/78a12c40-b306-11e6-905e-d634b76eb72d.png)

don't know what's a 83.5x83.5? Perhaps you know @chiaroscurosity ?

**Comment by chiaroscurosity** [comment]
I don't know why an 83.5px icon would be needed. I can make it that size and see what happens. Hopefully, the warning goes away. Are the icons for commenting and liking?

**Comment by seene-club** [comment]
Oh, it's 83.5@2x. So I think it just has to be 167x167!? Strange notation!

**Comment by chiaroscurosity** [comment]
[167px.zip](https://github.com/seene-club/Open-Seene/files/615027/167px.zip)

**Comment by seene-club** [comment]
icons finished. square versions do work.
