### ISSUE TITLE
FlickrAPI_keys.h file not found ?

### ISSUE THREAD

**Issue by langzhidubu** [seene-club/Open-Seene#8]
FlickrAPI_keys.h file not found ?

**Comment by seene-club** [comment]
yes, this is left out intentionally. See --> https://github.com/seene-club/Open-Seene/blob/master/Open%20Seene/.gitignore

The file contains the private API keys and secrets from Flickr.
You can get your own keys here: https://www.flickr.com/services/api/misc.api_keys.html

Here's the structure of the file without the keys:
```
//
//  FlickrAPI_keys.h
//  Open Seene
//
//

#ifndef FlickrAPI_keys_h
#define FlickrAPI_keys_h


#endif /* FlickrAPI_keys_h */

static NSString *flrAPIid  = @"<FlickrAPI-ID>";
static NSString *flrAPIKey = @"<FlickrAPI-Key>";
static NSString *flrSecret = @"<Flickr-Secret>";
static NSString *seeneGroupID = @"3075220@N22";
static NSString *agentString = @"Mozilla/5.0 (iOS; Open Seene App; en-en) AppleWebKit (KHTML, like Gecko) Safari";
```
